apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/pacaruso/argocd-helm.git
        revision: main
        directories:
          - path: dev/test-application/*
  template:
    metadata:
      name: "{{ index .path.segments 1 }}-{{ .path.basename }}"
      namespace: 'openshift-gitops'
    annotations:
      argocd.argoproj.io/manifest-generate-paths: .
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/pacaruso/argocd-helm.git
        targetRevision: main
        path: "{{ .path.path }}"
        helm:
          valueFiles:
          - Values.yaml
          - values.yaml
          ignoreMissingValueFiles: true
          releaseName: "{{ .path.basename }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        retry:
          limit: 2
          backoff:
            duration: '30s'
            maxDuration: '1m30s'
            factor: 2
          