---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotation:
    argocd.argoproj.io/sync-wave: '1'
  name: data1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotation:
    argocd.argoproj.io/sync-wave: '1'
  name: data2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi